api:
  prefix: api/v1/
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hotelmanagement?useSSL=false&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
      dialect: org.hibernate.dialect.MySQL8Dialect
      format_sql: true
#jwt:
#  expiration: 2592000
#  secretKey: I hava a dream
